Adding 2021 supplement survey to the package, which includes data about robbery, theft, feeling of safety and technology
datazoompuc/datazoom_social_Stata pull request #84
Opened 2023-04-20 17:44 UTC by AntonioBergallo

2023-04-24 18:23 UTC, FranciscoCavalcanti requested changes
Oi @AntonioBergallo 

Gostaria que você realize as seguintes tarefas para padronização dos nomes das PNAD Continuas Anuais:

1.  Padronizar o nome das PNAD Continuas Anuais da mesma forma que o IBGE oferece, ou seja, dividir as PNAD Continuas entre "visita" e "trimestre".

2.  Alterar todos os nomes da caixa de diálogo, conforme as mudanças sugeridas no ponto 1). Por exemplo, a opção "2016_sup_educ" na linha 17 deve ser alterada para "2016_visita2". 

3. Alterar todos os nomes da caixa de diálogo, conforme as mudanças sugeridas no ponto 1). Por exemplo, a opção "pnad_anual_educ" na linha 57 deve ser alterada para "pnad_anual_visita2". 

Certifique-se de que todos os nomes sejam alterados corretamente.

2023-04-24 18:23 UTC, FranciscoCavalcanti commented on PNAD_Continua/Anual/datazoom_pnadcont_anual.ado
> -					save PNADC_anual_2016_educ, replace
O dado original está escrito "PNADC_2016_trimestre2.txt" no entanto você alterou para "PNADC_anual_2016_visita2". O correto seria "PNADC_anual_2016_trimestre2".

2023-04-24 18:23 UTC, FranciscoCavalcanti commented on PNAD_Continua/Anual/datazoom_pnadcont_anual.ado
> +					save PNADC_anual_2016_visita4, replace
Averiguei que o dado original não se chama mais "PNADC_042016_tic.txt". Aparentemente mudou para "PNADC_2016_trimestre4.txt". É preciso averiguar.

2023-04-24 18:23 UTC, FranciscoCavalcanti commented on PNAD_Continua/Anual/datazoom_pnadcont_anual.ado
> +					}
Acho melhor mantermos o mesmo padrão de nomes adotado pelo IBGE. Por isso, sugiro mudar o nome do arquivo salvo para "PNADC_2021_trimestre4" mesmo.

2023-04-25 16:04 UTC, AntonioBergallo commented
I decided not to add new supplementary surveys until this PR is accepted and to adjust the years loop, so the package doesn't have huge changes all at once. The 2021 violence and TIC dictionary works for the years that only have the TIC, however, the violence columns return empty values. I could create a new dictionary for 2016-2019, so that the output doesn't have all these useless columns.

2023-05-09 20:26 UTC, closed without merging