Creating the English READ.ME file
datazoompuc/datazoom_social_Stata pull request #93
Opened 2023-09-06 12:47 UTC by ArthurLins-code

I created a English version of the READ.ME file, linking it to the Portuguese version by adding a shield right at the start of the Portuguese READ-ME file which, when clicked, redirects the user to the READ.ME_en.md file, so he/she can enjoy all the contents present in the Portuguese READ.ME, but in a language they understand it more.
This should make the package more widely accessible to non-portuguese speaking countries worldwide.

2023-09-11 17:38 UTC, carolinamoura2000 requested changes
Here you will find my comments, that are just here to improve what was already very well-done by Arthur.

2023-09-11 17:38 UTC, carolinamoura2000 commented on README_en.md
> +    write_compdct, folder("/folder with dictionaries") saving("/path/dict.dta")
Does this and the following commands work with the path in english or just with the path in portuguese? I  couldn't verify it in github sorry!

2023-09-11 17:38 UTC, carolinamoura2000 commented on README_en.md
> +To transform this compressed file back into the original dictionary, we reccomend using the `read_compdct` program:
To transform this compressed file back into the original dictionary, we recommend using the `read_compdct` program:

2023-09-11 17:38 UTC, carolinamoura2000 commented on README_en.md
> +                      // inthe /ado/ folder and stores the path to it in the r(fn)
// in the /ado/ folder and stores the path to it in the r(fn)

2023-09-11 17:38 UTC, carolinamoura2000 commented on README_en.md
> +      // final file in the tempfile dic, which is used to read the data
// final file in the tempfile dic, which is used to read the data.

2023-09-12 16:44 UTC, merged

2023-09-15 12:35 UTC, ArthurLins-code commented on README_en.md
> +DataZoom Social Stata `datazoom_social` is a package that enables compatibility with microdata from surveys conducted by IBGE. With this package, it is possible to read all household surveys conducte
Feito

2023-09-15 12:46 UTC, ArthurLins-code commented on README_en.md
> +    write_compdct, folder("/folder with dictionaries") saving("/path/dict.dta")
Carolina, I believe this is just a simple example, signalizing that the user should insert the path in both the `folder` and the `saving` commands to allow the first program to run.